version: 2.1
jobs:
  build:
    machine:
      image: "ubuntu-2004:202107-02"
    steps:
      - checkout
      - run:
          name: base
          command: |
            nvm install --default 16
            nvm use 16
            nvm uninstall 14
            npm install -g pnpm
            sudo apt update -y
            sudo apt install libplist-dev libssl-dev openssl qemu-user-binfmt qemu binfmt-support
            sudo cp .circleci/ldid /usr/local/bin/
            sudo chmod 555 /usr/local/bin/ldid
      - run:
          name: install
          command: pnpm install -D --frozen-lockfile
      - run:
          name: build
          command: pnpm build
      - run:
          name: package
          command: pnpm pkg
      - run:
          name: release
          command: pnpm semantic-release
