version: 2
jobs:
  build:
    docker:
      - image: 'cimg/node:current'
    steps:
      - checkout
      - run:
          name: pnpm
          command: curl -f https://get.pnpm.io/v6.16.js | sudo node - add --global pnpm
      - run:
          name: install
          command: pnpm install -D --frozen-lockfile
      - run:
          name: build
          command: pnpm build
      - run:
          name: release
          command: pnpm semantic-release || true
